name: neo_video_player_for_web_integration_tests
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  js: ^0.6.0
  neo_video_player_platform_interface:
    git: 
      url: https://github.com/MacjaZival/neo_video_player.git
      path: neo_video_player_platform_interface
  neo_video_player_web:
    git: 
      url: https://github.com/MacjaZival/neo_video_player.git
      path: neo_video_player_web

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
