name: neo_video_player_web
description: Web platform implementation of neo_video_player.
repository: https://github.com/flutter/packages/tree/main/packages/neo_video_player/video_player_web
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+neo_video_player%22
version: 2.0.15
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: neo_video_player
    platforms:
      web:
        pluginClass: VideoPlayerPlugin
        fileName: neo_video_player_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  neo_video_player_platform_interface:
    git: 
      url: https://github.com/MacjaZival/neo_video_player.git
      path: neo_video_player_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0

