name: neo_video_player_android
description: Android implementation of the neo_video_player plugin.
repository: https://github.com/flutter/packages/tree/main/packages/neo_video_player/video_player_android
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+neo_video_player%22
version: 2.4.0
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: neo_video_player
    platforms:
      android:
        dartPluginClass: AndroidVideoPlayer
        package: si.telekom.plugins.neovideoplayer
        pluginClass: VideoPlayerPlugin

dependencies:
  flutter:
    sdk: flutter
  neo_video_player_platform_interface:
    git: 
      url: https://github.com/MacjaZival/neo_video_player.git
      path: neo_video_player_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^2.0.1
  very_good_analysis: ^4.0.0

